// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/sandbox.proto

package sandboxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Exec          string                 `protobuf:"bytes,2,opt,name=exec,proto3" json:"exec,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env           []string               `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,5,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Stdin         []byte                 `protobuf:"bytes,6,opt,name=stdin,proto3" json:"stdin,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,7,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_api_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ExecuteRequest) GetExec() string {
	if x != nil {
		return x.Exec
	}
	return ""
}

func (x *ExecuteRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecuteRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

func (x *ExecuteRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Stdout        []byte                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	DurationMs    int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_api_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecuteResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type StreamChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamChunk_Stdout
	//	*StreamChunk_Stderr
	//	*StreamChunk_Progress
	//	*StreamChunk_Result
	Payload       isStreamChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChunk) Reset() {
	*x = StreamChunk{}
	mi := &file_api_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunk) ProtoMessage() {}

func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunk.ProtoReflect.Descriptor instead.
func (*StreamChunk) Descriptor() ([]byte, []int) {
	return file_api_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *StreamChunk) GetPayload() isStreamChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamChunk) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Payload.(*StreamChunk_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *StreamChunk) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Payload.(*StreamChunk_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *StreamChunk) GetProgress() float64 {
	if x != nil {
		if x, ok := x.Payload.(*StreamChunk_Progress); ok {
			return x.Progress
		}
	}
	return 0
}

func (x *StreamChunk) GetResult() *ExecuteResponse {
	if x != nil {
		if x, ok := x.Payload.(*StreamChunk_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isStreamChunk_Payload interface {
	isStreamChunk_Payload()
}

type StreamChunk_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type StreamChunk_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type StreamChunk_Progress struct {
	Progress float64 `protobuf:"fixed64,3,opt,name=progress,proto3,oneof"`
}

type StreamChunk_Result struct {
	Result *ExecuteResponse `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

func (*StreamChunk_Stdout) isStreamChunk_Payload() {}

func (*StreamChunk_Stderr) isStreamChunk_Payload() {}

func (*StreamChunk_Progress) isStreamChunk_Payload() {}

func (*StreamChunk_Result) isStreamChunk_Payload() {}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_api_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_api_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *CancelRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_api_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_api_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *CancelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_api_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_api_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *FileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_api_sandbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_api_sandbox_proto_rawDescGZIP(), []int{6}
}

func (x *ReadFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_api_sandbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_api_sandbox_proto_rawDescGZIP(), []int{7}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteFileRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_api_sandbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_api_sandbox_proto_rawDescGZIP(), []int{8}
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type FileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_api_sandbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_api_sandbox_proto_rawDescGZIP(), []int{9}
}

func (x *FileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FileInfoMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	ModTimeUnix   int64                  `protobuf:"varint,5,opt,name=mod_time_unix,json=modTimeUnix,proto3" json:"mod_time_unix,omitempty"`
	IsDir         bool                   `protobuf:"varint,6,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfoMsg) Reset() {
	*x = FileInfoMsg{}
	mi := &file_api_sandbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfoMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoMsg) ProtoMessage() {}

func (x *FileInfoMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoMsg.ProtoReflect.Descriptor instead.
func (*FileInfoMsg) Descriptor() ([]byte, []int) {
	return file_api_sandbox_proto_rawDescGZIP(), []int{10}
}

func (x *FileInfoMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfoMsg) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfoMsg) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfoMsg) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileInfoMsg) GetModTimeUnix() int64 {
	if x != nil {
		return x.ModTimeUnix
	}
	return 0
}

func (x *FileInfoMsg) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Entries       []*FileInfoMsg         `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_api_sandbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_api_sandbox_proto_rawDescGZIP(), []int{11}
}

func (x *ListFilesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListFilesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListFilesResponse) GetEntries() []*FileInfoMsg {
	if x != nil {
		return x.Entries
	}
	return nil
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Info          *FileInfoMsg           `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_api_sandbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_api_sandbox_proto_rawDescGZIP(), []int{12}
}

func (x *StatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StatResponse) GetInfo() *FileInfoMsg {
	if x != nil {
		return x.Info
	}
	return nil
}

type PortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerPort int32                  `protobuf:"varint,1,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortRequest) Reset() {
	*x = PortRequest{}
	mi := &file_api_sandbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortRequest) ProtoMessage() {}

func (x *PortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortRequest.ProtoReflect.Descriptor instead.
func (*PortRequest) Descriptor() ([]byte, []int) {
	return file_api_sandbox_proto_rawDescGZIP(), []int{13}
}

func (x *PortRequest) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

type PortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	HostPort      int32                  `protobuf:"varint,3,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	PublicUrl     string                 `protobuf:"bytes,4,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortResponse) Reset() {
	*x = PortResponse{}
	mi := &file_api_sandbox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortResponse) ProtoMessage() {}

func (x *PortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortResponse.ProtoReflect.Descriptor instead.
func (*PortResponse) Descriptor() ([]byte, []int) {
	return file_api_sandbox_proto_rawDescGZIP(), []int{14}
}

func (x *PortResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PortResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PortResponse) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *PortResponse) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_sandbox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_sandbox_proto_rawDescGZIP(), []int{15}
}

func (x *StatusRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	ActiveTasks   int32                  `protobuf:"varint,2,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	UptimeMs      int64                  `protobuf:"varint,3,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_sandbox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_sandbox_proto_rawDescGZIP(), []int{16}
}

func (x *StatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StatusResponse) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *StatusResponse) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

var File_api_sandbox_proto protoreflect.FileDescriptor

const file_api_sandbox_proto_rawDesc = "" +
	"\n" +
	"\x11api/sandbox.proto\x12\fs2aa.sandbox\x1a\x1bgoogle/protobuf/empty.proto\"\xbf\x01\n" +
	"\x0eExecuteRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x12\n" +
	"\x04exec\x18\x02 \x01(\tR\x04exec\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x10\n" +
	"\x03env\x18\x04 \x03(\tR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x05 \x01(\tR\n" +
	"workingDir\x12\x14\n" +
	"\x05stdin\x18\x06 \x01(\fR\x05stdin\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\a \x01(\x03R\ttimeoutMs\"\xce\x01\n" +
	"\x0fExecuteResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\fR\x06stderr\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\"\xa3\x01\n" +
	"\vStreamChunk\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12\x1c\n" +
	"\bprogress\x18\x03 \x01(\x01H\x00R\bprogress\x127\n" +
	"\x06result\x18\x04 \x01(\v2\x1d.s2aa.sandbox.ExecuteResponseH\x00R\x06resultB\t\n" +
	"\apayload\".\n" +
	"\rCancelRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\"*\n" +
	"\x0eCancelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"!\n" +
	"\vFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"V\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"N\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\"6\n" +
	"\fMkdirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\">\n" +
	"\fFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x98\x01\n" +
	"\vFileInfoMsg\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\x12\"\n" +
	"\rmod_time_unix\x18\x05 \x01(\x03R\vmodTimeUnix\x12\x15\n" +
	"\x06is_dir\x18\x06 \x01(\bR\x05isDir\"x\n" +
	"\x11ListFilesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x123\n" +
	"\aentries\x18\x03 \x03(\v2\x19.s2aa.sandbox.FileInfoMsgR\aentries\"m\n" +
	"\fStatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12-\n" +
	"\x04info\x18\x03 \x01(\v2\x19.s2aa.sandbox.FileInfoMsgR\x04info\"4\n" +
	"\vPortRequest\x12%\n" +
	"\x0econtainer_port\x18\x01 \x01(\x05R\rcontainerPort\"z\n" +
	"\fPortResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1b\n" +
	"\thost_port\x18\x03 \x01(\x05R\bhostPort\x12\x1d\n" +
	"\n" +
	"public_url\x18\x04 \x01(\tR\tpublicUrl\".\n" +
	"\rStatusRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"f\n" +
	"\x0eStatusResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12!\n" +
	"\factive_tasks\x18\x02 \x01(\x05R\vactiveTasks\x12\x1b\n" +
	"\tuptime_ms\x18\x03 \x01(\x03R\buptimeMs2\x97\x06\n" +
	"\x0eSandboxService\x12F\n" +
	"\aExecute\x12\x1c.s2aa.sandbox.ExecuteRequest\x1a\x1d.s2aa.sandbox.ExecuteResponse\x12J\n" +
	"\rExecuteStream\x12\x1c.s2aa.sandbox.ExecuteRequest\x1a\x19.s2aa.sandbox.StreamChunk0\x01\x12C\n" +
	"\x06Cancel\x12\x1b.s2aa.sandbox.CancelRequest\x1a\x1c.s2aa.sandbox.CancelResponse\x12E\n" +
	"\bReadFile\x12\x19.s2aa.sandbox.FileRequest\x1a\x1e.s2aa.sandbox.ReadFileResponse\x12G\n" +
	"\tWriteFile\x12\x1e.s2aa.sandbox.WriteFileRequest\x1a\x1a.s2aa.sandbox.FileResponse\x12G\n" +
	"\tListFiles\x12\x19.s2aa.sandbox.FileRequest\x1a\x1f.s2aa.sandbox.ListFilesResponse\x12C\n" +
	"\n" +
	"DeleteFile\x12\x19.s2aa.sandbox.FileRequest\x1a\x1a.s2aa.sandbox.FileResponse\x12B\n" +
	"\bMkdirAll\x12\x1a.s2aa.sandbox.MkdirRequest\x1a\x1a.s2aa.sandbox.FileResponse\x12=\n" +
	"\x04Stat\x12\x19.s2aa.sandbox.FileRequest\x1a\x1a.s2aa.sandbox.StatResponse\x12C\n" +
	"\n" +
	"ExposePort\x12\x19.s2aa.sandbox.PortRequest\x1a\x1a.s2aa.sandbox.PortResponse\x12F\n" +
	"\tGetStatus\x12\x1b.s2aa.sandbox.StatusRequest\x1a\x1c.s2aa.sandbox.StatusResponseB)Z'github.com/narcilee7/S2AA/api/sandboxpbb\x06proto3"

var (
	file_api_sandbox_proto_rawDescOnce sync.Once
	file_api_sandbox_proto_rawDescData []byte
)

func file_api_sandbox_proto_rawDescGZIP() []byte {
	file_api_sandbox_proto_rawDescOnce.Do(func() {
		file_api_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_sandbox_proto_rawDesc), len(file_api_sandbox_proto_rawDesc)))
	})
	return file_api_sandbox_proto_rawDescData
}

var file_api_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_sandbox_proto_goTypes = []any{
	(*ExecuteRequest)(nil),    // 0: s2aa.sandbox.ExecuteRequest
	(*ExecuteResponse)(nil),   // 1: s2aa.sandbox.ExecuteResponse
	(*StreamChunk)(nil),       // 2: s2aa.sandbox.StreamChunk
	(*CancelRequest)(nil),     // 3: s2aa.sandbox.CancelRequest
	(*CancelResponse)(nil),    // 4: s2aa.sandbox.CancelResponse
	(*FileRequest)(nil),       // 5: s2aa.sandbox.FileRequest
	(*ReadFileResponse)(nil),  // 6: s2aa.sandbox.ReadFileResponse
	(*WriteFileRequest)(nil),  // 7: s2aa.sandbox.WriteFileRequest
	(*MkdirRequest)(nil),      // 8: s2aa.sandbox.MkdirRequest
	(*FileResponse)(nil),      // 9: s2aa.sandbox.FileResponse
	(*FileInfoMsg)(nil),       // 10: s2aa.sandbox.FileInfoMsg
	(*ListFilesResponse)(nil), // 11: s2aa.sandbox.ListFilesResponse
	(*StatResponse)(nil),      // 12: s2aa.sandbox.StatResponse
	(*PortRequest)(nil),       // 13: s2aa.sandbox.PortRequest
	(*PortResponse)(nil),      // 14: s2aa.sandbox.PortResponse
	(*StatusRequest)(nil),     // 15: s2aa.sandbox.StatusRequest
	(*StatusResponse)(nil),    // 16: s2aa.sandbox.StatusResponse
}
var file_api_sandbox_proto_depIdxs = []int32{
	1,  // 0: s2aa.sandbox.StreamChunk.result:type_name -> s2aa.sandbox.ExecuteResponse
	10, // 1: s2aa.sandbox.ListFilesResponse.entries:type_name -> s2aa.sandbox.FileInfoMsg
	10, // 2: s2aa.sandbox.StatResponse.info:type_name -> s2aa.sandbox.FileInfoMsg
	0,  // 3: s2aa.sandbox.SandboxService.Execute:input_type -> s2aa.sandbox.ExecuteRequest
	0,  // 4: s2aa.sandbox.SandboxService.ExecuteStream:input_type -> s2aa.sandbox.ExecuteRequest
	3,  // 5: s2aa.sandbox.SandboxService.Cancel:input_type -> s2aa.sandbox.CancelRequest
	5,  // 6: s2aa.sandbox.SandboxService.ReadFile:input_type -> s2aa.sandbox.FileRequest
	7,  // 7: s2aa.sandbox.SandboxService.WriteFile:input_type -> s2aa.sandbox.WriteFileRequest
	5,  // 8: s2aa.sandbox.SandboxService.ListFiles:input_type -> s2aa.sandbox.FileRequest
	5,  // 9: s2aa.sandbox.SandboxService.DeleteFile:input_type -> s2aa.sandbox.FileRequest
	8,  // 10: s2aa.sandbox.SandboxService.MkdirAll:input_type -> s2aa.sandbox.MkdirRequest
	5,  // 11: s2aa.sandbox.SandboxService.Stat:input_type -> s2aa.sandbox.FileRequest
	13, // 12: s2aa.sandbox.SandboxService.ExposePort:input_type -> s2aa.sandbox.PortRequest
	15, // 13: s2aa.sandbox.SandboxService.GetStatus:input_type -> s2aa.sandbox.StatusRequest
	1,  // 14: s2aa.sandbox.SandboxService.Execute:output_type -> s2aa.sandbox.ExecuteResponse
	2,  // 15: s2aa.sandbox.SandboxService.ExecuteStream:output_type -> s2aa.sandbox.StreamChunk
	4,  // 16: s2aa.sandbox.SandboxService.Cancel:output_type -> s2aa.sandbox.CancelResponse
	6,  // 17: s2aa.sandbox.SandboxService.ReadFile:output_type -> s2aa.sandbox.ReadFileResponse
	9,  // 18: s2aa.sandbox.SandboxService.WriteFile:output_type -> s2aa.sandbox.FileResponse
	11, // 19: s2aa.sandbox.SandboxService.ListFiles:output_type -> s2aa.sandbox.ListFilesResponse
	9,  // 20: s2aa.sandbox.SandboxService.DeleteFile:output_type -> s2aa.sandbox.FileResponse
	9,  // 21: s2aa.sandbox.SandboxService.MkdirAll:output_type -> s2aa.sandbox.FileResponse
	12, // 22: s2aa.sandbox.SandboxService.Stat:output_type -> s2aa.sandbox.StatResponse
	14, // 23: s2aa.sandbox.SandboxService.ExposePort:output_type -> s2aa.sandbox.PortResponse
	16, // 24: s2aa.sandbox.SandboxService.GetStatus:output_type -> s2aa.sandbox.StatusResponse
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_sandbox_proto_init() }
func file_api_sandbox_proto_init() {
	if File_api_sandbox_proto != nil {
		return
	}
	file_api_sandbox_proto_msgTypes[2].OneofWrappers = []any{
		(*StreamChunk_Stdout)(nil),
		(*StreamChunk_Stderr)(nil),
		(*StreamChunk_Progress)(nil),
		(*StreamChunk_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_sandbox_proto_rawDesc), len(file_api_sandbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_sandbox_proto_goTypes,
		DependencyIndexes: file_api_sandbox_proto_depIdxs,
		MessageInfos:      file_api_sandbox_proto_msgTypes,
	}.Build()
	File_api_sandbox_proto = out.File
	file_api_sandbox_proto_goTypes = nil
	file_api_sandbox_proto_depIdxs = nil
}
